= **Kirk** - pragmatic UI test automation

Doc Writer <http://automation-remarks.com>

:TestVanillaBrowser: ../../src/test/kotlin/com/automation/remarks/kirk/test/vanila/TestVanillaBrowser.kt
:BrowserUsageTest: ../../src/test/kotlin/com/automation/remarks/kirk/test/oop/BrowserUsageTest.kt
:ToDo: ../../src/test/kotlin/com/automation/remarks/kirk/test/example/TodoPage.kt
:TodoAngularTest: ../../src/test/kotlin/com/automation/remarks/kirk/test/example/TodoAngularTest.kt
:KElementTest: ../../src/test/kotlin/com/automation/remarks/kirk/test/vanila/KElementTest.kt

Kirk is a browser automation library for Kotlin. It's basically a Selenium-WebDriver wrapper library inspired by Selenide and Geb.

- No Page Factory
- No @FindBy
- Pragmatic DSL
- Informative error messages
- Automatic Driver Management
- Straightforward Page Objects
- Chrome browser is a default
- Automatic screenshots on fail

== Installation

Kirk is available in Maven Central. The latest version is **{VERSION}**

.Gradle
[subs="attributes"]
----
compile group: 'com.automation-remarks', name: 'kirk', version: '{VERSION}'
----

.Maven
[source, xml]
----
<dependency>
    <groupId>com.automation-remarks</groupId>
    <artifactId>kirk</artifactId>
    <version>{VERSION}</version>
</dependency>
----

== Basic usage

=== Simple script example

You are able to write tests using DSL

[source, java]
----
include::{TestVanillaBrowser}[tags=testCanDriveScripts]
----

=== Browser instance usage example

Straightforward OOP way

[source, java]
----
include::{BrowserUsageTest}[tags=testСanRunBrowser]
----

=== Error messages

----
      failed while waiting 4 seconds
      to assert text
      for element located {By.cssSelector: #button}
      reason: condition did not match
            expected: [K]irk
            actual: []irk

            screenshot: file:///kirk/build/reports/screen_1499188301800.png
----

== The Browser

The entry point to Kirk is the Browser object.

The default constructor of Browser class instantiates ChromeDriver.
----
import com.automation.remarks.kirk.Browser

val browser = Browser()
----

However, if you prefer to specify the driver implementation,
you can pass it using secondary constructor

----
import com.automation.remarks.kirk.Browser

val browser = Browser(FirefoxDriver())
----

Browser instance can be configured using code example below:

[source, java]
----
val chrome = Browser(FirefoxDriver()).with {
            baseUrl = "http://local:8080"
            holdOpen = true
            startMaximized = false
            screenSize = listOf(640,480)
}
----

Any property set this way will override any settings coming from the config mechanism.

=== The `drive()` method

The Browser class has a static method drive(), that makes a process of writing tests much easier.

[source, java]
----
include::{TestVanillaBrowser}[tags=testCanDriveScripts]
----

This is pretty much the same as

[source, java]
----
include::{BrowserUsageTest}[tags=testСanRunBrowser]
----

The closure is evaluated against created browser instance.
You can access all top level methods and properties declared in the Browser class.

=== Base URL support

Browser instances maintain a baseUrl property that is used to resolve all relative URLs.
The value can be defined using configuration or can be explicitly set on the browser.

For example your site URL is `http://locahost:8086/`. You can use is as shown below

.kirk.properties
----
kirk.baseUrl=http://localhost:8086/
----

And now method `open()` use relative path

[source, java]
----
Browser.drive {
   open("/")
   ...
}
----

Or you can define base URL using browser instance

[source, java]
----
val browser = Browser().with{
     baseUrl = "http://localhost:8086/"
}

browser.open("/")
----

=== Absolute URL support

As well as parent url, Kirk allows to navigate pages using absolute url

[source, java]
----
Browser.drive {
   open("http://localhost:8086/login")
   at(::LoginPage).loginAs("admin","admin")
}
----

Absolute url can be defined inside author <email> page object

[source, java]
----
class StartPage(browser: Browser) : Page(browser) {
    override val url: String?
        get() = "http://localhost:8086/login"
}

Browser.drive {
    to(::StartPage).element("#header").should(have.text("Kirk"))
}
----

NOTE: It is better to use relative path, because of maintenance reason. For example
you can easily manage properties for different environments Dev, QA, Stage etc.

=== Page object support

Page objects is one of the pattern that is highly recommended to use in Test Automation projects.
Kirk page can define an optional url variable that will be used to navigate to that page. This is done with the `to()` method.

[source, java]
----
class StartPage(browser: Browser) : Page(browser) {
    override val url: String?
        get() = "/"
}

Browser.drive {
    to(::StartPage).element("#header").should(have.text("Kirk"))
}
----

The `to()` method makes a request to the resolved URL and navigates to the target page. Method `to()` is overloaded so it can accept
lambda as a second parameter and points to the instance of that page.

[source, java]
----
Browser.drive {
    to(::StartPage) {
       element("#header").should(have.text("Kirk"))
    }
}
----

Page lambda scope has access to all public methods and variable declared inside page object class.

=== Auto close browser support

Browser will automatically close at the end of either single test execution or
bunch of tests. This behaviour can be changed by setting property **holdOpen=true**
in a config file or system property.

== The Page

To use Page Object pattern, you create subclasses of Page that define with a help of powerful DSL that allows you to refer to content by meaningful names instead of tag names or CSS expressions.

.Todo page example
[source, java]
----
include::{ToDo}[tags=TodoPage]
----

.Test class
[source, java]
----
include::{TodoAngularTest}[tags=TodoAngularTest]
----

== Alerts

Nowadays alerts is not widely used in modern web applications, however Kirk allows to interact with alert windows

.accept alert
[source, java]
----
Browser.drive {
    to(url)
    alert.accept()
}
----

.dismiss alert
[source, java]
----
Browser.drive {
    to(url)
    alert.dismiss()
}
----

.verify alert text
[source, java]
----
Browser.drive {
    to(url)
    assert(alert.text == "Hello buddy")
}
----

== Web page interaction

Test automation engineers spend a lot of time writing query
selectors and element locators to find element on a given page.

Kirk provides a set of methods that helps to interact with page elements.

=== The `element()` function

The element function is the access point to the page content.
It returns a KElement object that is a representation of WebElement that we interact with.

==== Using CSS locators

Function `element()` accepts a String parameter as a cssLocator

.find element by id = header
[source, java]
----
element("#header")
----

.find element by css class = .paginator
[source, java]
----
element(".paginator")
----

.find element by tag = footer
[source, java]
----
element("footer")
----

==== Using Webdriver's By locator

For `element()` there is an equivalent signature where an instance of WebDriver’s By selector can be used instead of a String.

.find element by id = header
[source, java]
----
element(By.id("#header"))
----

.find element by css class = .paginator
[source, java]
----
element(By.className(".paginator"))
----

.find element by tag = footer
[source, java]
----
element(By.tagName("footer"))
----

IMPORTANT: Using CSS selectors is the preferred way to use in Kirk.
For XPath selectors another convenience mechanism is provided.

==== Using XPATH locators

XPATH is a powerful element location mechanism that can be used in Kirk

.find element by xpath = //div[@text()='name']
[source, java]
----
element(byXpath("//div[@text()='name']"))
----

or equivalent

.find element by xpath = //div[@text()='name']
[source, java]
----
element(By.xpath("//div[@text()='name']"))
----

==== Using `element()` composition

It is also possible to locate element. To do this, simply call the **element()** function chain

Let's look at example below:

[source, html]
----
<div>
    <ul class="list">
        <li>Один</li>
        <li>Два</li>
        <li>Три</li>
    </ul>
</div>
----

.find element "a" inside "div"
[source, java]
----
include::{KElementTest}[tags=composition]
----

Also there are some additional useful methods

- firstChild
- lastChild
- parent
- children

[source, java]
----
include::{KElementTest}[tags=child]
----

[source, java]
----
include::{KElementTest}[tags=parent]
----



NOTE: It's better to use CSS or Xpath locators to achieve the same result

== The `KElement`

The KElement class is a representation of WebElement, we want to interact with.

==== Press enter

[source, java]
----
element("#selector").pressEnter()
----

==== Upload file

KElement have useful methods that helps to write tests. Example file upload

.upload file
[source, java]
----
include::{KElementTest}[tags=uploadFile]
----

== Configuration

Configuration can be made using several ways:

- kirk.properties file
- System properties
- Custom property directly in code

Configuration is made by using http://owner.aeonbits.org/docs/variables-expansion/[Java Owner library]

=== Kirk property file

Just create file **kirk.properties** in **src/main/resources** or **src/test/resources** of the project
It's possible to set such variables:

----
kirk.timeout = 4000
kirk.poolingInterval = 0.1
kirk.startMaximized = true
kirk.holdOpen = false
kirk.screenSize = 1920,1080          // empty by default
kirk.baseUrl = http://localhost:8086 // empty by default
----

=== System properties

As well as using property file, you can pass configuration via System properties

----
System.setProperty("kirk.timeout","6000")
System.setProperty("kirk.startMaximized","true")
System.setProperty("kirk.baseUrl","http://192.168.0.1:8086")
----

IMPORTANT: System properties have higher priority, so that by setting system
property you override value from property file

=== Custom property in source code

You can define property directly in code

[source, java]
----
val chrome = Browser(FirefoxDriver()).with {
            baseUrl = "http://local:8080"
            holdOpen = true
            startMaximized = false
            screenSize = listOf(640,480)
}
----

=== Custom configuration interface

Define custom interface of type **Configuration**

[source, java]
----
@Sources("classpath:browser.properties")
interface CustomConfig : Configuration {
    @DefaultValue("2000")
    @Key("firefox.timeout")
    override fun timeout(): Int

    @Key("holdOpen")
    @DefaultValue("true")
    override fun holdOpen(): Boolean
}
----

Use it in your code

[source, java]
----
val browser = Browser().with {
     config = loadConfig(CustomConfig::class)
}
----

You can use it for single instance alongside with System properties and
**kirk.properties** file

== About

=== Contributors

- Sergey Pirogov

=== Changelog

==== v0.7

- Browser factory added
- Configuration support added
- Element variables added: title, text etc.

==== v0.6

- First public release
