= Kirk - pragmatic UI test automation

Doc Writer <http://automation-remarks.com>

:VERSION: 0.7
:TestVanillaBrowser: ../../src/test/kotlin/com/automation/remarks/kirk/test/vanila/TestVanillaBrowser.kt
:BrowserUsageTest: ../../src/test/kotlin/com/automation/remarks/kirk/test/oop/BrowserUsageTest.kt

Kirk is a browser automation library for Kotlin. It's basically a Selenium-WebDriver wrapper library inspired by Selenide and Geb.

- No Page Factory
- No @FindBy
- Pragmatic DSL
- Informative error messages
- Automatic Driver Management
- Straightforward Page Objects
- Chrome browser is a default
- Automatic screenshots on fail

== Installation

Kirk is available in Maven Central

.Gradle
[subs="attributes"]
----
compile group: 'com.automation-remarks', name: 'kirk', version: '{VERSION}'
----

.Maven
[source, xml]
----
<dependency>
    <groupId>com.automation-remarks</groupId>
    <artifactId>kirk</artifactId>
    <version>{VERSION}</version>
</dependency>
----

== Basic usage

=== Simple script example

You are able to write tests using DSL

[source, java]
----
include::{TestVanillaBrowser}[tags=testCanDriveScripts]
----

=== Browser instance usage example

Straightforward OOP way

[source, java]
----
include::{BrowserUsageTest}[tags=testСanRunBrowser]
----

=== Error messages

----
      failed while waiting 4 seconds
      to assert text
      for element located {By.cssSelector: #button}
      reason: condition did not match
            expected: [K]irk
            actual: []irk

            screenshot: file:///kirk/build/reports/screen_1499188301800.png
----

== The Browser

The entry point to Kirk is the Browser object.

The default constructor of Browser class instantiates ChromeDriver.
----
import com.automation.remarks.kirk.Browser

val browser = Browser()
----

However, if you prefer to specify the driver implementation,
you can pass it using secondary constructor

----
import com.automation.remarks.kirk.Browser

val browser = Browser(FirefoxDriver())
----

Browser instance can be configured using code example below:

[source, java]
----
val chrome = Browser(FirefoxDriver()).with {
            baseUrl = "http://local:8080"
            holdOpen = true
            startMaximized = false
            screenSize = listOf(640,480)
}
----

Any property set this way will override any settings coming from the config mechanism.

=== The drive() method

The Browser class have a static method drive(), that makes process of writing tests a lot easies.

[source, java]
----
include::{TestVanillaBrowser}[tags=testCanDriveScripts]
----

This is pretty much the same as

[source, java]
----
include::{BrowserUsageTest}[tags=testСanRunBrowser]
----

The closure is evaluated against created browser instance.
You can access all top level methods and properties declared in the Browser class.

=== Base URL support

Browser instances maintain a baseUrl property that is used to resolve all relative URLs.
The value can be defined using configuration or can be explicitly set on the browser.

For example your site URL is `http://locahost:8086/`. You can use is as shown below

.kirk.properties
----
kirk.baseUrl=http://localhost:8086/
----

And now method `open()` use relative path

----
Browser.drive {
   open("/")
   ...
}
----

Or you can define base URL using browser instance

----
val browser = Browser().with{
     baseUrl = "http://localhost:8086/"
}

browser.open("/")
----

=== Page object support

Page objects is one of the pattern that is highly recommended to use in Test Automation projects.
Kirk page can define an optional url variable that will be used to navigate to that page. This is done with the `to()` method.

[source, java]
----
class StartPage(browser: Browser) : Page(browser) {
    override val url: String?
        get() = "/"
}

Browser.drive {
    to(::StartPage).element("#header").should(have.text("Kirk"))
}
----

The `to()` method makes a request to the resolved URL and navigates to the target page. Method `to()` is overloaded so it can accept
lambda as a second parameter and points to the instance of that page.

[source, java]
----
Browser.drive {
    to(::StartPage) {
       element("#header").should(have.text("Kirk"))
    }
}
----

Page lambda scope have access to all public methods and variable declared inside page object class.

== The Page

The Page class description

== Configuration

Configuration can be made using several ways:

- kirk.properties file
- System properties
- Custom property directly in code

=== Kirk property file

Just create file **kirk.properties** in **src/main/resources** or **src/test/resources** of the project
It's possible to set such variables:

----
kirk.timeout = 4000
kirk.poolingInterval = 0.1
kirk.startMaximized = true
kirk.holdOpen = false
kirk.screenSize = 1920,1080          // empty by default
kirk.baseUrl = http://localhost:8086 // empty by default
----

=== System properties

As well as using property file, you can pass configuration via System properties

----
System.setProperty("kirk.timeout","6000")
System.setProperty("kirk.startMaximized","true")
System.setProperty("kirk.baseUrl","http://192.168.0.1:8086")
----

IMPORTANT: System properties have higher priority, so that by setting system
property you override value from property file

=== Custom property in source code

You can define property directly in code

[source, java]
----
val chrome = Browser(FirefoxDriver()).with {
            baseUrl = "http://local:8080"
            holdOpen = true
            startMaximized = false
            screenSize = listOf(640,480)
}
----

=== Custom configuration interface

Define custom interface of type **Configuration**

[source, java]
----
@Sources("classpath:browser.properties")
interface CustomConfig : Configuration {
    @DefaultValue("2000")
    @Key("firefox.timeout")
    override fun timeout(): Int

    @Key("holdOpened")
    @DefaultValue("true")
    override fun holdOpened(): Boolean
}
----

Use it in your code

[source, java]
----
val browser = Browser().with {
     config = loadConfig(CustomConfig::class)
}
----

You can use it for single instance alongside with System properties and
**kirk.properties** file
